version: "3.8"

services:
  declared-frontend:
    init: true
    image: schmelczera/declared-frontend
    ports:
      - "80"
    networks:
      - network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 16M
        reservations:
          cpus: "0.1"
          memory: 16M
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
        monitor: 10s
      restart_policy:
        condition: on-failure
        window: 30s

networks:
  network:
    driver: overlay
