version: '3.8'

services:
  decla-red-server:
    init: true
    image: schmelczera/decla-red-server
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        window: 30s

networks:
  network:
