name: Deploy everything
on:
  push:
    branches:
      - master
jobs:
  build-ingress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch with lfs
      uses: actions/checkout@master
      with:
        lfs: true
      
    - name: Setup auth tokens
      run: |      
        # Docker Hub
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push ingress
      run: |
        docker build . -t schmelczera/declared-ingress
        docker push schmelczera/declared-ingress
      working-directory: ingress

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch with lfs
      uses: actions/checkout@master
      with:
        lfs: true
      
    - name: Setup auth tokens
      run: |      
        # Docker Hub
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend
      run: |
        docker build . -t schmelczera/declared-frontend
        docker push schmelczera/declared-frontend
      working-directory: frontend

  deploy:
    runs-on: ubuntu-latest
    needs:
    - build-frontend
    - build-ingress
    steps:      
    - name: Setup auth tokens
      run: |
        # SSH key
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 400 ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no root@decla.red uptime

    - name: Stack up
      run: |
          DOCKER_HOST=ssh://root@decla.red docker stack up declared -c docker-compose.yml
      working-directory: infrastructure
